"""LogCombiner-BEAST1

This module takes multiple log or tree files from BEAST (v1.10.4/5) as input and returns a single combined log or tree file as output.

Params:
    trees (boolean): use this option to combine tree log files (default is false)
    decimal (boolean): this option converts numbers from scientific to decimal notation (default is false)
    burnin (integer): number of states to be considered as 'burn-in'
    resample (integer): resample the log files to this frequency (the original sampling frequency must be a factor of this value)
    scale (float): a scaling factor that will multiply any time units by this value
    strip (boolean): strip out all annotations (trees only)
    renumber (boolean): this option renumbers output states consecutively
    input:
        infiles (list of strings): input log/tree files
    output:
        outfile (string): output combined log/tree file
"""

configfile: "config/config.yaml"

indir=config["input_namespace"]
outdir=config["output_namespace"]
params=config["params"]

rule target:
    input:
        infile = expand(
            "results/{indir}/{filename}",
            indir=indir,
            filename=params["input"]["infiles"]
        ),
    output:
        outfile = expand(
            "results/{outdir}/{filename}",
            outdir=outdir,
            filename=params["output"]["outfile"]
        )
    conda:
        "envs/conda.yaml"
    params:
        trees=params["trees"],
        decimal=params["decimal"],
        burnin=params["burnin"],
        resample=params["resample"],
        scale=params["scale"],
        strip=params["strip"],
        renumber=params["renumber"] 
    shell:
        """
        logcombiner \
            $(if [ {params.trees} == true ]; then echo "-trees"; else echo ""; fi) \
            $(if [ {params.decimal} == true ]; then echo "-decimal"; else echo ""; fi) \
            -burnin {params.burnin} \
            -resample {params.resample} \
            -scale {params.scale} \
            $(if [ {params.strip} == true ]; then echo "-strip"; else echo ""; fi) \
            $(if [ {params.renumber} == true ]; then echo "-renumber"; else echo ""; fi) \
            {input.infile} {output.outfile}
        """
