input_namespace: "in"
output_namespace: "out"
params:
  chain_length: 1000000
  screen_log_every: 10000
  file_log_every: 10000
  tree_log_every: 10000
  const_pop_size_model:
    initial_value: 1
    lower: 0
  strict_clock_model:
    clock_rate: 0.0001
  hky_model:
    frequencies:
      A: 0.25
      C: 0.25
      T: 0.25
      G: 0.25
    kappa:
      initial_value: 2
      lower: 0
  priors:
    kappa:
      lognormal:
        mean: 1
        stdev: 1.25
        offset: 0
    frequencies:
      uniform:
        lower: 0
        upper: 1
  input:
    alignment: "alignment.fasta"
    template: ""
  output:
    xml: "output.xml"
    filename_stem: "output"