input_namespace: "in"
output_namespace: "out"
params:
  trees: false
  decimal: false
  burnin: 1000000
  resample: 10000
  scale: 1
  strip: false
  renumber: false
  input:
    infiles:
      - "run-1.log"
      - "run-2.log"
  output:
    outfile: "combined.log"
