input_namespace: "in"
output_namespace: "out"
params:
  input:
    infile: "dta_annotated_tree.mcc.tree"
    fertree:
      attribute: "location"
      latest_time: null
      source: "origin"
      destination: "destination"
  output:
    tl_table: "lineage_table.tsv"
    plot:
      outfile: "lineage_size_distribution.png"
      max_ntaxa: 1000
      title: "Lineage size distribution"
      x: 7.5
      y: 4.5
      pdf: false